# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

FIREBASE_CLI_TOKEN = ENV["FIREBASE_CLI_TOKEN"]

default_platform(:android)

platform :android do

  desc "Submit a new beta build to Google Play"
  lane :beta do
    sh "flutter build appbundle -v"
    upload_to_play_store(
      track: 'beta',
      release_status: 'draft',  # TODO: remove after enable beta
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      )
  end

  desc "Promote beta track to prod"
  lane :promote_to_production do
    upload_to_play_store(
      track: 'beta',
      track_promote_to: 'production',
      )
  end

  desc "Submit a new production build to Google Play"
  lane :production do
    sh "flutter build appbundle -v"
    # upload_to_play_store(
    #   track: 'production',
    #   release_status: 'draft', # TODO: remove after enable production
    #   aab: '../build/app/outputs/bundle/release/app-release.aab',
    # )
  end

  desc "Deploy with Firebase"
  lane :firebase do
    sh "flutter build apk"
    # firebase_app_distribution(
    #   app: "1:978524361958:android:35a1ee96e3b9440bcbd727",
    #   testers: "jimmy.to.goldenowl@gmail.com",
    #   release_notes: sh("git log -1 --pretty='%s'"),
    #   firebase_cli_path: "/usr/local/bin/firebase",
    #   apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
    #   firebase_cli_token: FIREBASE_CLI_TOKEN
    # )
  end
end
